# 检索的关键词
keywords:
    "agent": ["agent", ]
    "Time Series": ["Time Series", ]
    "graph": ["graph representation", ]
# 搜索的时间，从当天凌晨往回推  pastDays 天。使用 UTC 时间，北京时间为 UTC+8
pastDays: 5
# 是否需要翻译摘要，如果需要，则必须在 translate.py 中将 deepseek_apikey 修改为自己的 key
translate: True

base_url: 'https://export.arxiv.org/api/query?'
start: 0
total_results: 200              # want xxx total results
results_per_iteration: 200      # xxx results at a time
wait_time: 5                    # number of seconds to wait beetween calls

saveBasePath: "resultPapers"
